import Link from 'next/link'

export const metadata = {
  title: 'Privacy Policy - Fit Coach',
  description: 'Privacy Policy for Fit Coach Application',
}

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-dark">
      <div className="container-custom py-24">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-primary hover:text-primary-light transition-colors mb-8"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
          Back to home
        </Link>

        <h1 className="text-4xl sm:text-5xl font-bold mb-4">Privacy Policy</h1>
        <p className="text-white/60 text-lg mb-12">
          <strong>Last updated: December 16, 2025</strong>
        </p>

        <div className="prose prose-invert max-w-none space-y-8">
          <section>
            <p className="text-white/80 leading-relaxed mb-6">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p className="text-white/80 leading-relaxed">
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>
          </section>

          <section className="pt-6">
            <h2 className="text-3xl font-bold mb-6">Interpretation and Definitions</h2>
            
            <h3 className="text-2xl font-bold mb-4 text-primary">Interpretation</h3>
            <p className="text-white/80 leading-relaxed mb-6">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h3 className="text-2xl font-bold mb-4 text-primary">Definitions</h3>
            <p className="text-white/80 mb-4">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc list-inside space-y-3 text-white/80 pl-4">
              <li><strong className="text-white">Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong className="text-white">Application</strong> refers to Fit Coach, the mobile application provided by the Company.</li>
              <li><strong className="text-white">Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to the individual operator of Fit Coach, based in France.</li>
              <li><strong className="text-white">Country</strong> refers to: France</li>
              <li><strong className="text-white">Device</strong> means any device that can access the Service such as a smartphone, tablet or computer.</li>
              <li><strong className="text-white">Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong className="text-white">Service</strong> refers to the Application and Website.</li>
              <li><strong className="text-white">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
              <li><strong className="text-white">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
              <li><strong className="text-white">Website</strong> refers to Fit Coach, accessible from fit-coach.app</li>
              <li><strong className="text-white">You</strong> means the individual accessing or using the Service.</li>
            </ul>
          </section>

          <section className="pt-6">
            <h2 className="text-3xl font-bold mb-6">Data Minimization Principle</h2>
            <p className="text-white/80 leading-relaxed mb-4">
              We only collect data that is <strong className="text-primary">strictly necessary</strong> to deliver the features of the Application. We do not collect data unrelated to fitness coaching or app functionality.
            </p>
            <div className="bg-dark-light border border-primary/20 rounded-xl p-6 mb-4">
              <p className="text-white font-semibold mb-3">We do NOT access:</p>
              <ul className="list-disc list-inside space-y-2 text-white/80">
                <li>Your photos or camera</li>
                <li>Your contacts</li>
                <li>Your files or documents</li>
                <li>Your microphone</li>
                <li>Your precise location (GPS)</li>
              </ul>
            </div>
            <p className="text-white/80 leading-relaxed">
              We only collect fitness-related information that You explicitly provide to personalize Your workout experience.
            </p>
          </section>

          <section className="pt-6">
            <h2 className="text-3xl font-bold mb-6">Collecting and Using Your Personal Data</h2>
            
            <h3 className="text-2xl font-bold mb-4 text-primary">Types of Data Collected</h3>
            
            <h4 className="text-xl font-bold mb-3 text-white">Personal Data</h4>
            <p className="text-white/80 leading-relaxed mb-4">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc list-inside space-y-2 text-white/80 mb-6 pl-4">
              <li>Email address</li>
              <li>First name</li>
              <li>Age</li>
              <li>Weight and height</li>
              <li>Fitness objectives and goals</li>
              <li>Physical fitness level</li>
              <li>Available workout equipment</li>
              <li>Physical limitations</li>
              <li>Workout history and performance data</li>
            </ul>

            <h4 className="text-xl font-bold mb-3 text-white">Usage Data</h4>
            <p className="text-white/80 leading-relaxed mb-4">
              Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), device type, operating system version, the time and date of Your use of the Service, workout duration and performance metrics, and other diagnostic data.
            </p>

            <h4 className="text-xl font-bold mb-3 text-white">Information Collected while Using the Application</h4>
            <p className="text-white/80 leading-relaxed mb-4">
              While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:
            </p>
            <ul className="list-disc list-inside space-y-2 text-white/80 pl-4">
              <li>Health and fitness data (workout sessions, exercises performed, weights lifted, repetitions, sets, workout duration, estimated calories burned)</li>
              <li><strong className="text-white">Apple HealthKit data</strong> (optional): If You grant permission, We may access Your health and fitness data from Apple Health (such as workouts, heart rate, calories burned). This data is used solely to provide You with personalized workout recommendations and is stored securely on Your device and Our servers. We do not share Your HealthKit data with third parties for advertising or marketing purposes.</li>
            </ul>
            
            <div className="bg-primary/10 border-2 border-primary/30 rounded-xl p-6 mt-4">
              <h4 className="text-lg font-bold text-white mb-2">🏥 HealthKit Data Notice</h4>
              <p className="text-white/80 text-sm leading-relaxed">
                Fit Coach integrates with Apple HealthKit to sync Your fitness data. <strong className="text-white">Your HealthKit data is never sold to advertisers or third parties.</strong> We use this data exclusively to provide You with personalized fitness coaching and track Your progress. You can revoke HealthKit permissions at any time in Your device Settings.
              </p>
            </div>
          </section>

          <section className="pt-6">
            <h2 className="text-3xl font-bold mb-6">Legal Basis for Processing Personal Data (GDPR)</h2>
            <p className="text-white/80 leading-relaxed mb-4">
              If You are a resident of the European Economic Area (EEA), We process Your Personal Data under the following legal bases in accordance with the General Data Protection Regulation (GDPR):
            </p>
            <ul className="list-disc list-inside space-y-3 text-white/80 pl-4">
              <li><strong className="text-white">Consent (Article 6(1)(a) GDPR)</strong>: When You create an account and provide Your fitness information.</li>
              <li><strong className="text-white">Contract Necessity (Article 6(1)(b) GDPR)</strong>: Processing Your data is necessary to provide You with the Service.</li>
              <li><strong className="text-white">Legitimate Interest (Article 6(1)(f) GDPR)</strong>: We process anonymized and aggregated data to improve our Service.</li>
            </ul>
            <p className="text-white/80 leading-relaxed mt-4">
              You have the right to withdraw Your consent at any time by contacting Us at{' '}
              <a href="mailto:contact@fit-coach.app" className="text-primary hover:text-primary-light underline">
                contact@fit-coach.app
              </a>
            </p>
          </section>

          <section className="pt-6">
            <h2 className="text-3xl font-bold mb-6">AI Disclaimer</h2>
            <div className="bg-primary/10 border-2 border-primary/30 rounded-xl p-6">
              <p className="text-white/90 leading-relaxed mb-4">
                Our AI coach provides fitness guidance based on your inputs and training data. While we strive for accuracy,{' '}
                <strong className="text-primary">AI-generated suggestions may contain errors and should not be used as medical advice</strong>.
              </p>
              <p className="text-white font-semibold mb-3">Important:</p>
              <ul className="list-disc list-inside space-y-2 text-white/80">
                <li>AI-generated responses may sometimes be inaccurate</li>
                <li>Users should not rely solely on the AI for health or medical decisions</li>
                <li>Always consult a qualified healthcare professional before starting any new exercise program</li>
                <li>The AI coach is designed to provide general fitness guidance, not personalized medical advice</li>
              </ul>
            </div>
          </section>

          <section className="pt-6">
            <h2 className="text-3xl font-bold mb-6">Third-Party Service Providers</h2>
            <p className="text-white/80 mb-4">We employ third-party companies and services to facilitate our Service:</p>
            
            <div className="space-y-4">
              <div className="bg-dark-light rounded-xl p-5 border border-white/10">
                <h4 className="text-lg font-bold text-white mb-2">Supabase</h4>
                <p className="text-white/70 text-sm">Authentication, data storage (servers in Northern Europe - Sweden)</p>
              </div>
              
              <div className="bg-dark-light rounded-xl p-5 border border-white/10">
                <h4 className="text-lg font-bold text-white mb-2">OpenAI</h4>
                <p className="text-white/70 text-sm">AI coaching - chat messages processed by GPT models</p>
              </div>
              
              <div className="bg-dark-light rounded-xl p-5 border border-white/10">
                <h4 className="text-lg font-bold text-white mb-2">Apple In-App Purchase</h4>
                <p className="text-white/70 text-sm">Payment processing - we do not store your payment information</p>
              </div>
              
              <div className="bg-dark-light rounded-xl p-5 border border-white/10">
                <h4 className="text-lg font-bold text-white mb-2">Superwall</h4>
                <p className="text-white/70 text-sm">Subscription management and paywall tracking</p>
              </div>

              <div className="bg-dark-light rounded-xl p-5 border border-white/10">
                <h4 className="text-lg font-bold text-white mb-2">Mixpanel</h4>
                <p className="text-white/70 text-sm">Analytics and user behavior tracking to improve the app experience. We collect anonymized usage data (e.g., features used, session duration). <strong className="text-white">No personally identifiable information is shared.</strong></p>
              </div>

              <div className="bg-dark-light rounded-xl p-5 border border-white/10">
                <h4 className="text-lg font-bold text-white mb-2">AppsFlyer</h4>
                <p className="text-white/70 text-sm">Mobile attribution and marketing analytics. AppsFlyer helps us understand which marketing campaigns are most effective. Data collected includes device information and app interactions. <strong className="text-white">No health or fitness data is shared with AppsFlyer.</strong></p>
              </div>

              <div className="bg-dark-light rounded-xl p-5 border border-white/10">
                <h4 className="text-lg font-bold text-white mb-2">Apple HealthKit</h4>
                <p className="text-white/70 text-sm">Integration with Apple Health to sync fitness data (workouts, heart rate, calories). <strong className="text-white">HealthKit data remains on Your device and Our secure servers. We never share HealthKit data with third parties for advertising or marketing purposes.</strong> This complies with Apple's HealthKit Data Use Policy.</p>
              </div>
            </div>

            <div className="bg-red-500/10 border-2 border-red-500/30 rounded-xl p-6 mt-6">
              <h4 className="text-lg font-bold text-red-400 mb-3">⚠️ Important Privacy Notice</h4>
              <p className="text-white/80 text-sm leading-relaxed mb-3">
                <strong className="text-white">HealthKit Data Protection:</strong> In accordance with Apple's policies, Your health data from HealthKit is:
              </p>
              <ul className="list-disc list-inside space-y-1 text-white/70 text-sm pl-4">
                <li>Never used for advertising or marketing purposes</li>
                <li>Never sold to third parties, data brokers, or advertisers</li>
                <li>Never shared with analytics platforms (Mixpanel, AppsFlyer) for commercial purposes</li>
                <li>Used exclusively to provide You with personalized fitness coaching</li>
                <li>Stored securely with encryption</li>
              </ul>
            </div>
          </section>

          <section className="pt-6">
            <h2 className="text-3xl font-bold mb-6">Your Data Protection Rights (GDPR)</h2>
            <p className="text-white/80 leading-relaxed mb-4">
              If You are a resident of the European Economic Area (EEA), You have certain data protection rights:
            </p>
            <ul className="list-disc list-inside space-y-2 text-white/80 pl-4 mb-4">
              <li><strong className="text-white">Access</strong>: Request copies of Your Personal Data</li>
              <li><strong className="text-white">Rectification</strong>: Request correction of inaccurate or incomplete data</li>
              <li><strong className="text-white">Erasure</strong>: Request deletion of Your Personal Data</li>
              <li><strong className="text-white">Restriction</strong>: Request restriction of processing</li>
              <li><strong className="text-white">Data Portability</strong>: Request transfer of Your data to another service</li>
              <li><strong className="text-white">Object</strong>: Object to processing of Your Personal Data</li>
              <li><strong className="text-white">Withdraw Consent</strong>: Withdraw consent at any time</li>
            </ul>
            <p className="text-white/80 leading-relaxed">
              To exercise these rights, contact Us at{' '}
              <a href="mailto:contact@fit-coach.app" className="text-primary hover:text-primary-light underline">
                contact@fit-coach.app
              </a>
            </p>
          </section>

          <section className="pt-6">
            <h2 className="text-3xl font-bold mb-6">Delete Your Personal Data</h2>
            <p className="text-white/80 leading-relaxed mb-4">
              You may delete Your Account and all associated Personal Data at any time by:
            </p>
            <ol className="list-decimal list-inside space-y-2 text-white/80 pl-4 mb-4">
              <li>Opening the Application</li>
              <li>Going to Settings (Paramètres)</li>
              <li>Selecting "Delete Account" (Supprimer mon compte)</li>
            </ol>
            <p className="text-white/80 leading-relaxed">
              Alternatively, contact Us at{' '}
              <a href="mailto:contact@fit-coach.app" className="text-primary hover:text-primary-light underline">
                contact@fit-coach.app
              </a>
            </p>
          </section>

          <section className="pt-6">
            <h2 className="text-3xl font-bold mb-6">Security of Your Personal Data</h2>
            <p className="text-white/80 leading-relaxed mb-4">
              We use industry-standard security measures to protect Your data, including:
            </p>
            <ul className="list-disc list-inside space-y-2 text-white/80 pl-4 mb-4">
              <li>Encryption of data in transit (HTTPS/TLS)</li>
              <li>Encryption of data at rest</li>
              <li>Secure authentication protocols</li>
              <li>Regular security updates</li>
            </ul>
            <p className="text-white/80 leading-relaxed">
              However, no method of transmission over the Internet is 100% secure. While We strive to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>
          </section>

          <section className="pt-6">
            <h2 className="text-3xl font-bold mb-6">Children's Privacy</h2>
            <p className="text-white/80 leading-relaxed">
              Our Service is not intended for anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us at{' '}
              <a href="mailto:contact@fit-coach.app" className="text-primary hover:text-primary-light underline">
                contact@fit-coach.app
              </a>
            </p>
          </section>

          <section className="pt-6">
            <h2 className="text-3xl font-bold mb-6">Changes to this Privacy Policy</h2>
            <p className="text-white/80 leading-relaxed">
              We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date. You are advised to review this Privacy Policy periodically for any changes.
            </p>
          </section>

          <section className="pt-6 pb-12">
            <h2 className="text-3xl font-bold mb-6">Contact Us</h2>
            <p className="text-white/80 leading-relaxed mb-4">
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <div className="bg-primary/10 border border-primary/30 rounded-xl p-6">
              <p className="text-white font-semibold">
                By email:{' '}
                <a href="mailto:contact@fit-coach.app" className="text-primary hover:text-primary-light underline">
                  contact@fit-coach.app
                </a>
              </p>
            </div>
          </section>
        </div>
      </div>
    </main>
  )
}

